#!/usr/bin/env bash
set -e


COLCON_OPTS="--cmake-args -DCMAKE_BUILD_TYPE=Release -DCMAKE_LIBRARY_PATH=/usr/local/cuda/lib64/stubs"

export LIBRARY_PATH=/usr/lib/OpenNI2/Drivers:$LIBRARY_PATH
colcon build $COLCON_OPTS $@
